### ISSUE TITLE
compatible with latest mupdf?

### ISSUE THREAD

**Issue by ousia** [rk700/python-fitz#1]
Are your bindings compatible with the latest mupdf-1.3?

Many thanks for your work,

Pablo

**Comment by JorjMcKie** [comment]
@jonathanhearn 
I am determined to give this a try, and I am in contact with @rk700.
Have you done anything yet that can be shared?

**Comment by rk700** [comment]
@JorjMcKie @jonathanhearn , I started a new branch for MuPDF v1.7. For now I can think of 2 points to note:

1. The MuPDF library is written in C, and it's the user's job to manage the memory allocation/deallocation. But certainly we would not like to expose that in our python binding, so we need to make sure that object constructor/destructor functions are mapped to python class methods correctly.

2. The generated .c file is following C99, which I know is not supported by VC

**Comment by ousia** [comment]
I think it makes sense to change the title.

**Comment by rk700** [comment]
1.7 support is almost done. You can checkout to the 1.7 branch and have a try. Though I haven't ever compiled it on windows.

The API changes a little to be more object orientated, and I add a large amount of comments to the demo.py. Now the demo.py covers most of the features, and it can be a good example to follow.

And I'll merge this 1.7 branch to master when it's ok, and maybe we can just have a new branch for the legacy 1.2 code.

**Comment by ousia** [comment]
@rk700, would it be possible to have the 1.7 branch merged to master?

In my opinion the 1.2 code should be removed. It is old code that needs an outdated mupdf version. And if anyone would like to see the code, it is in the git history (or whichever its name should be).

**Comment by JorjMcKie** [comment]
I tend to sort of agree.

I do not know however, how large the user community of python-fitz 1.2 is.

It seems, that the Python user interface is going to change with 1.7 – to an extent that will break old 1.2 code.

So, either:

*         1.2 users are very few – therefore do not give a damn about them altogether,  or

*         let them live with the old code if they want, and supply a new 1.7 version side-by-side – as an upgrade option, maybe even with migration hints.

 

I really am convinced, that a new 1.7 based python-fitz (let’s call it „PyMuPDF“) will have a lot of potential in the Python community, because of its obvious advantages. No other Python-PDF tool is competitive in terms of features + performance.

Once we are there, I alone could publish several ‘production’-ready Python-PDF applications.

 

As a resume, if 1.2 will be a functional and syntactical subset of 1.7: kill it.

Otherwise – let it go stale over time and provide migration options.

 

Von: Pablo Rodríguez [mailto:notifications@github.com] 
Gesendet: Samstag, 23. Mai 2015 16:21
An: rk700/python-fitz
Cc: Jorj X. McKie
Betreff: Re: [python-fitz] compatible with latest mupdf? (#1)

 

@rk700 <https://github.com/rk700> , would it be possible to have the 1.7 branch merged to master?

In my opinion the 1.2 code should be removed. It is old code that needs an outdated mupdf version. And if anyone would like to see the code, it is in the git history (or whichever its name should be).

**Comment by rk700** [comment]
Sure. 1.2 is pretty old.

I'll tag the current master as 'v1.2', and then merge the 1.7 branch into master. In this way, we'll get the 1.7 code when pulling, and we still have a reference to 1.2 code.

**Comment by rk700** [comment]
I've merged 1.7 into master, and there are still some work left:
1. Make sure that it can be compiled without errors on windows. Some setup scripts may be helpful.
2. Make sure that the demos can work. Since I changed some python class names/methods in 1.7.
3. Provide pre-complied modules for windows.
4. Add document for the 1.7 if needed.

**Comment by ousia** [comment]
@rk700, I see that there is no `setup.py` for Linux setup after the 1.7 merge.

Would it be possible to have it back?

**Comment by rk700** [comment]
@ousia yes the `setup.py` is back now.

**Comment by JorjMcKie** [comment]
Thanks to recent changes to the SWIG interface file by @rk700, the Windows version has been successfully built. Therefore I have taken the liberty to close the corresponding issue.

The demo.py program works fine. As it covers large areas of fitz functionality, including an outline generator, let's delete the PDF_outline.py.

As the overall issue "1.7" is concerned, I think the successfull end of the mission is in sight!

I believe we should start considering the final content of the new version.
"Easy to use" should be the guiding principle here.

As a consequence, I suggest to keep windows users (probably the largest potential user group) free from generating MuPDF, and even python-fitz.
Everything such a guy should need to do is installing the two items "fitz.py" and "_fitz.pyd" (which is the name of the DLL under Windows), and he is ready to go within 2 minutes after download!

I can not say whether a similar approach is possible for the numerous other plaforms, MAC, UNIXes, LINUXes, etc. Would be good if it were possible for the most popular ones (LINUX), no doubt.

Another consequence is of course overhauling the documentation ...

**Comment by JorjMcKie** [comment]
**Another success:**  
PDF_display.py is working under windows ...

**Comment by rk700** [comment]
Right, I agree that pre-compiled modules will be of great help for windows users. I do not have a windows box though, so I think maybe @JorjMcKie could help us do the work.

I decided to keep the version number consistent with MuPDF, so this would be 1.7.0, and when we add more symbols in the future, we will have 1.7.1, and so on. Let's just wait for a couple of days for any possible modifications for 1.7.0. I'll close this issue then, and we can start building modules after that.

**Comment by JorjMcKie** [comment]
Hi everyone,

 

I sure can provide the _fitz DLL for windows.

I just don’t know how to upload binary data into GITHUB. The size of of _fitz.pyd is roughly 9 Megabytes, or 4.4 Megabytes when compressed with UPX.

And I also am absolutely willing to supply the two libraries libmupdf.lib / libthirdparty.lib (roughly 35 Megabytes) for those users who want to do a distutils setup by themselves.

In essence:

1)      Use fitz.py  + _fitz.pyd ==> no build work at all

2)      Use fitz.py + fitz_wrap.c  + libmupdf.lib + libthirdparty.lib ==> setup.py build/install will be required.

 

Best regards

Jorj

 

Von: Ruikai Liu [mailto:notifications@github.com] 
Gesendet: Montag, 25. Mai 2015 07:27
An: rk700/python-fitz
Cc: Jorj X. McKie
Betreff: Re: [python-fitz] compatible with latest mupdf? (#1)

 

Right, I agree that pre-compiled modules will be of great help for windows users. I do not have a windows box though, so I think maybe @JorjMcKie <https://github.com/JorjMcKie>  could help us do the work.

I decided to keep the version number consistent with MuPDF, so this would be 1.7.0, and when we add more symbols in the future, we will have 1.7.1, and so on. Let's just wait for a couple of days for any possible modifications for 1.7.0. I'll close this issue then, and we can start building modules after that.

**Comment by rk700** [comment]
@JorjMcKie, I haven't upload binaries either. But it seems that we could upload binaries by creating release: https://help.github.com/articles/distributing-large-binaries/

**Comment by JorjMcKie** [comment]
Ahh – ok. I will study this.

Thanks!

 

Von: Ruikai Liu [mailto:notifications@github.com] 
Gesendet: Montag, 25. Mai 2015 07:56
An: rk700/python-fitz
Cc: Jorj X. McKie
Betreff: Re: [python-fitz] compatible with latest mupdf? (#1)

 

@JorjMcKie <https://github.com/JorjMcKie> , I haven't upload binaries either. But it seems that we could upload binaries by creating release: https://help.github.com/articles/distributing-large-binaries/

**Comment by JorjMcKie** [comment]
@ousia:
python-fitz for the current MuPDF 1.7a is available / usable. I think we should close this issue. Though work does remain, it is on a whole different level as this rather global issue, but as you opened it, it is up to you.

**Comment by ousia** [comment]
@JorjMckie, I totally agree with you.

Issue should be closed now.
