### ISSUE TITLE
variable names in PDF_display.py

### ISSUE THREAD

**Issue by ousia** [rk700/python-fitz#14]
@JorjMcKie, `PDF_display.py` contains two variable names that may not be obvious to everyone?

Would you agree with the replacement of `szr10` and `szr20` with `BoxSizerVertical` and `BoxSizerHorizontal`?

I would make the merge request myself, but first I need to be sure I’m not missing something (I don’t code  :worried:).

**Comment by JorjMcKie** [comment]
hi @ousia, no problem at all. It's just an abbreviation I used for "sizer". As these items do not mean anything in particular, but are just elements to organize the screen layout in a vertical or horizontal sense, I didn't bother to give them meaningfull names. Actually these things do not even need the "self." prefix, because they are not required outsize that class.
Well, that being said - go ahead, absolutely fine with me.
BTW., what do you think about the progress we (or, rather, Ruikai) have been making?
It seems, we already are beyond critical technical bugs. The functionality is more or less complete again, and I am currently working on documentation.
And that's good timing, too, because @rk700, our C-programming god will from now on again be a lot less available than he recently has been.
Let's stay in contact on this thing. I do have time, but my C expertise is **very** insufficient. It's a lot better with the rest of the technical stuff.

**Comment by JorjMcKie** [comment]
Hi @ousia, I have tested the PDF_display.py after variable names changes - it works!

**Comment by ousia** [comment]
> hi @ousia, no problem at all. It's just an abbreviation I used for "sizer". As these items do not mean anything in particular, but are just elements to organize the screen layout in a vertical or horizontal sense, I didn't bother to give them meaningfull names. Actually these things do not even need the "self." prefix, because they are not required outsize that class.

@JorjMcKie, thanks for the explanation about the `self.` (I knew early modern philosophy was important [but I didn’t know why :smiley:]).

In programming terminology, would it that be making a variable global/local?

> Well, that being said - go ahead, absolutely fine with me.

Merge request already done.

> BTW., what do you think about the progress we (or, rather, Ruikai) have been making?

I’m impressed. I wish I could find the time to package python-fitz (I have to find out first how to do it :smile:) for Fedora.

> It seems, we already are beyond critical technical bugs. The functionality is more or less complete again, and I am currently working on documentation.

Sorry, but I couldn’t check it yet.

> And that's good timing, too, because @rk700, our C-programming god will from now on again be a lot less available than he recently has been.

I would say timing was perfect.

> Let's stay in contact on this thing. I do have time, but my C expertise is very insufficient. It's a lot better with the rest of the technical stuff.

If you allow me a comment, knowledge is like money. First, we tend to think we have less than we actually have. And there are lots of people than have way less than you. Or even some that have really nothing.

That being said, many thanks for your dedication to this project.

**Comment by JorjMcKie** [comment]
A clarification about "self.":
When you program a class, it is like a model. It becomes some "real", namely an object, if you use it like  
``dlg = PDFdisplay(None)``
With this, the object ``dlg`` is being created and every occurence of "self.variable" inside the the class definition of PDFdisplay is from now on a known variable (or function name) throughout the program under the name ``dlg.variable``. Variables inside the class definition without the self prefix will never be known outside, and are therefore used to compute something internal to the class definition, or rather object creation process. In so far, yes, there are similarities to local variables (e.g. inside a function).

**Comment by JorjMcKie** [comment]
Hi @ousia,
I have made some additions.  
* added a new function to the ``Document`` class called ToC (table of contents). This function iterates through the outline items and creates a list of them like [[level, title, page], ...].  
* added a doc/html directory to the repository as a very 1st draft of documentation. It is still incomplete and buggy, but if you want, have a look at it, especially the tutorial should be close to finished.  
* added a wiki page "Status / what's new?"

Regards,
Jorj

**Comment by ousia** [comment]
@JorjMcKie, many thanks for all the good work you are putting into this project.

Many thanks also for clarifying the `self.` also.

I’m interested in using MuPDF for PDF presentations in full screen.

**Comment by JorjMcKie** [comment]
@ousia,
well I do have time, because I am retired :-), so this is just part of my hobbies (among them primarily mathematics, evolutionary science theory, physics, ...).

As for your goal "full screen presentations":
Assuming wxPython as the dialog manager, the following steps would be required:
* Determine the size of the displaying screen (width and height in pixels)
* Using the PDFdisplay.py as a starting point, adjust its size specification accordingly to maximize screen usage.
* Calculate the remaining space on the screen for a PDF page, i.e. the maximum size remaining for ``PDFimage``.
* For every PDF page to be displayed: scale the page rectangle to a maximum such that the result has width and height values less than or equal to the corresponding ``PDFimage`` values.
* Then put the scaled PDF page to the screen.

With this you still have a pesky window header and this "command line" appearing on the screen, but it may be a start.

**Comment by ousia** [comment]
> well I do have time, because I am retired :-),

@JorjMcKie, then, you earned it :smile:.

> so this is just part of my hobbies (among them primarily mathematics, evolutionary science theory, physics, ...).

My background is in humanities, so these hobbies are rather tortures to me :wink:.

When I find some time, I hope I can write a sample file which would fit as a demo.
